# Generated by Django 3.2.9 on 2023-10-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productingredient',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
