# Generated by Django 3.2.9 on 2023-10-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_app', '0002_alter_productingredient_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ingredients',
            field=models.ManyToManyField(through='back_app.ProductIngredient', to='back_app.Ingredient'),
        ),
    ]
